spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 1
        min-idle: 0
    timeout:
      